packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@types/node': ^22.15.29
  '@types/react-transition-group': ^4.4.12
  typescript: ~5.8.3
  animejs: ^4.0.2
  react-transition-group: ^4.4.5
  '@biomejs/biome': ^2.4.16
  '@vitejs/plugin-react-swc': ^3.9.0
  husky: ^9.1.7
  vite: ^6.3.5
  cross-env: ^7.0.3
  rollup-plugin-visualizer: ^6.0.1
